export const GET_TODOLIST_PENDING = 'GET_TODOLIST_PENDING';
export const GET_TODOLIST_FULLFILLED = 'GET_TODOLIST_FULLFILLED';
export const GET_TODOLIST_REJECTED = 'GET_TODOLIST_REJECTED';

export const GET_METHOD = 'GET_METHOD';
export const PUT_METHOD = 'PUT_METHOD';
export const DELETE_METHOD = 'DELETE_METHOD';
export const ADD_METHOD = 'ADD_METHOD';
